// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnTapTuVung.Data;

#nullable disable

namespace OnTapTuVung.Migrations
{
    [DbContext(typeof(Connect))]
    [Migration("20260328150617_manh1")]
    partial class manh1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnTapTuVung.Models.HSK", b =>
                {
                    b.Property<int>("IdHSK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHSK"));

                    b.Property<int>("LoaiHSK")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.HasKey("IdHSK");

                    b.ToTable("HSKs");

                    b.HasData(
                        new
                        {
                            IdHSK = 1,
                            LoaiHSK = 1
                        },
                        new
                        {
                            IdHSK = 2,
                            LoaiHSK = 2
                        },
                        new
                        {
                            IdHSK = 3,
                            LoaiHSK = 3
                        },
                        new
                        {
                            IdHSK = 4,
                            LoaiHSK = 4
                        },
                        new
                        {
                            IdHSK = 5,
                            LoaiHSK = 5
                        },
                        new
                        {
                            IdHSK = 6,
                            LoaiHSK = 6
                        });
                });

            modelBuilder.Entity("OnTapTuVung.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HanViet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdHSK")
                        .HasColumnType("integer");

                    b.Property<string>("Nghia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Pinyn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TuLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TuVung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdHSK");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("OnTapTuVung.Models.Vocabulary", b =>
                {
                    b.HasOne("OnTapTuVung.Models.HSK", "HSK")
                        .WithMany("Vocabularies")
                        .HasForeignKey("IdHSK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HSK");
                });

            modelBuilder.Entity("OnTapTuVung.Models.HSK", b =>
                {
                    b.Navigation("Vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
