services:
  - type: web
    name: hoc-tieng-trung
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1